/**
 * Enum para las opciones de configuración provenientes del .env
 *
 * En teoría se tiene que sincronizar el contenido de este archivo con la
 * validación en app.module.ts y obviamente el archivo .env|dotenv
 */
export enum ConfigKeys {
  GOOGLE_APPLICATION_CREDENTIALS = 'GOOGLE_APPLICATION_CREDENTIALS',
  MORGAN_TYPE = 'MORGAN_TYPE',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION = 'JWT_EXPIRATION',
  SENTRY_DSN = 'SENTRY_DSN',
  API_ROUTE = 'API_ROUTE',
  CREATE_USERS = 'CREATE_USERS',
  FIRST_PASSWORD = 'FIRST_PASSWORD',
  MYSQL_DB = 'MYSQL_DB',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_USER = 'MYSQL_USER',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
  MYSQL_ROOT_PASSWORD = 'MYSQL_ROOT_PASSWORD',
  API_SWAGGER = 'API_SWAGGER',
  PORT = 'PORT',
  SEND_USER_EMAILS = 'SEND_USER_EMAILS',
  SMTP_IGNORE_TLS = 'SMTP_IGNORE_TLS',
  SMTP_HOST = 'SMTP_HOST',
  SMTP_SECURE = 'SMTP_SECURE',
  SMTP_PORT = 'SMTP_PORT',
  SMTP_USER = 'SMTP_USER',
  SMTP_PASSWORD = 'SMTP_PASSWORD',
  SMTP_FROM_NAME = 'SMTP_FROM_NAME',
  SMTP_FROM_EMAIL = 'SMTP_FROM_EMAIL',
  TWILIO_ID = 'TWILIO_ID',
  TWILIO_KEY = 'TWILIO_KEY',
  TWILIO_NUMBER = 'TWILIO_NUMBER',
  FB_APP_ID = 'FB_APP_ID',
  FB_APP_SECRET = 'FB_APP_SECRET',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_SECRET = 'GOOGLE_SECRET',
  BASE_URL = 'BASE_URL',
  EMAILS_INBOX = 'EMAILS_INBOX',
  SITE_NAME = 'SITE_NAME',
  NODE_ENV = 'NODE_ENV',
}
