import {MigrationInterface, QueryRunner} from "typeorm";

export class reset1621450478255 implements MigrationInterface {
    name = 'reset1621450478255'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("CREATE TABLE `rules` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `name` varchar(50) NOT NULL, `description` varchar(150) NULL, `value` varchar(50) NOT NULL, UNIQUE INDEX `IDX_b5749378ee460e67696a7518d4` (`uuid`), UNIQUE INDEX `IDX_ea1cb877c529e67a39e2be4657` (`value`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `profiles` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `name` varchar(50) NOT NULL, UNIQUE INDEX `IDX_2c0c7196c89bdcc9b04f29f3fe` (`uuid`), UNIQUE INDEX `IDX_4e9da7cade0e9edd393329bb32` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `users` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `passwordToken` varchar(500) NULL, `passwordTokenDate` timestamp NULL, `email` varchar(150) NOT NULL, `firstName` varchar(50) NOT NULL, `lastName` varchar(50) NOT NULL, `password` varchar(150) NOT NULL, `validEmail` tinyint NOT NULL DEFAULT 0, `emailToken` varchar(500) NULL, `rules` text NULL, `profileId` int NOT NULL, `houseId` int NULL, `facebookId` varchar(100) NULL, `regType` varchar(50) NOT NULL DEFAULT 'SYSTEM', `regData` json NULL, `picUrl` varchar(250) NULL, `googleId` varchar(50) NULL, `isMain` tinyint NOT NULL DEFAULT 0, UNIQUE INDEX `IDX_951b8f1dfc94ac1d0301a14b7e` (`uuid`), UNIQUE INDEX `IDX_97672ac88f789774dd47f7c8be` (`email`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `houseComments` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `comment` text NOT NULL, `authorized` tinyint NOT NULL DEFAULT 0, `userId` int NULL, `houseId` int NULL, UNIQUE INDEX `IDX_1cb1775299c76dab26b0344dce` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `masters` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` varchar(150) NOT NULL, `descripcion` text NULL, `html` text NULL, `houseId` int NOT NULL, UNIQUE INDEX `IDX_3557a21feed9f2081e0678cef2` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `houses` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `rating` float NULL, `limiteBrands` int NOT NULL DEFAULT '0', `limiteProducts` int NOT NULL DEFAULT '0', `email` varchar(150) NOT NULL, `nombre` varchar(150) NOT NULL, `descripcion` text NULL, `html` text NULL, `calle` varchar(100) NOT NULL, `numExt` varchar(10) NULL, `numInt` varchar(10) NULL, `colonia` varchar(100) NULL, `municipio` varchar(100) NULL, `localidad` varchar(100) NULL, `estado` varchar(50) NOT NULL, `likes` int NOT NULL DEFAULT '0', UNIQUE INDEX `IDX_5a47aaa8bc31d505a3b16cad02` (`uuid`), UNIQUE INDEX `IDX_3365dc20e45b6d2576db3d30a4` (`email`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `brandComments` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `comment` text NOT NULL, `authorized` tinyint NOT NULL DEFAULT 0, `userId` int NULL, `brandId` int NULL, UNIQUE INDEX `IDX_a8acc9fa5069c8d546ac7b0e19` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `brands` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `rating` float NULL, `nombre` varchar(150) NOT NULL, `descripcion` text NULL, `html` text NULL, `likes` int NOT NULL DEFAULT '0', `houseId` int NOT NULL DEFAULT '0', UNIQUE INDEX `IDX_8502686214ddaf3c16aeb2475a` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `regions` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` varchar(150) NOT NULL, `estado` varchar(250) NOT NULL, `descripcion` text NOT NULL, `html` text NULL, `lat` float NOT NULL DEFAULT '0', `lng` float NOT NULL DEFAULT '0', `altitude` float NOT NULL DEFAULT '0', `estateNumber` float NOT NULL DEFAULT '0', UNIQUE INDEX `IDX_a624c5554287d4034798478a6b` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `agaves` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` text NOT NULL, `descripcion` text NOT NULL, `nombreCientifico` text NULL, `nombresConocidos` text NULL, `distribucion` text NULL, `comentarioTaxonomico` text NULL, `habitat` text NULL, `uso` text NULL, `probabilidadExistencia` text NULL, `html` text NULL, UNIQUE INDEX `IDX_0a493669ddc4365a0339173e8c` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `flavors` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` varchar(150) NOT NULL, `html` text NULL, UNIQUE INDEX `IDX_c089087c9ead1061cb0b9f5704` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `shops` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` varchar(150) NOT NULL, `descripcion` text NOT NULL, `formattedAddress` varchar(200) NULL, `addressComponents` text NULL, `url` varchar(100) NULL, `placeId` varchar(50) NULL, UNIQUE INDEX `IDX_072498f4079793b73da14c63ab` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `mezcalTypes` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` varchar(150) NOT NULL, `descripcion` text NOT NULL, UNIQUE INDEX `IDX_44741720475c1fd87b9bd52ce7` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `productComments` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `comment` text NOT NULL, `authorized` tinyint NOT NULL, `userId` int NULL, `productId` int NULL, UNIQUE INDEX `IDX_9f52cb406e348e1039d7449179` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `productFavorites` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `userId` int NULL, `productId` int NULL, UNIQUE INDEX `IDX_12015674033f1e5f0d8c57c086` (`uuid`), UNIQUE INDEX `product_favorites` (`userId`, `productId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `productLikes` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `userId` int NULL, `productId` int NULL, UNIQUE INDEX `IDX_4c726761d40c6ed3afd0f310f2` (`uuid`), UNIQUE INDEX `product_likes` (`userId`, `productId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `cooking` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` varchar(150) NOT NULL, `descripcion` varchar(250) NOT NULL, UNIQUE INDEX `IDX_34d3e15110d10debca394179b2` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `distilling` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` varchar(150) NOT NULL, `descripcion` varchar(250) NOT NULL, UNIQUE INDEX `IDX_aae0770d4db841e9578c9b97bf` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `fermenting` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` varchar(150) NOT NULL, `descripcion` varchar(250) NOT NULL, UNIQUE INDEX `IDX_0d0f15acacb3a684f4815da6c7` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `milling` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` varchar(150) NOT NULL, `descripcion` varchar(250) NOT NULL, UNIQUE INDEX `IDX_895c479772745b4dd5e55e1452` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `products` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` varchar(150) NOT NULL, `descripcion` text NULL, `html` text NULL, `score` float NULL, `rating` float NOT NULL DEFAULT '0', `price` float NULL, `likes` int NOT NULL DEFAULT '0', `colorAspect` varchar(150) NULL, `agingMaterial` varchar(150) NULL, `agingTime` int NOT NULL DEFAULT '0', `alcoholVolume` int NOT NULL DEFAULT '0', `distillingsNumber` int NOT NULL DEFAULT '0', `ltProduced` int NOT NULL DEFAULT '0', `brandId` int NOT NULL, `regionId` int NOT NULL, `mezcalTypeId` int NOT NULL, `organolepticas` json NULL, `masterId` int NULL, `cookingId` int NULL, `millingId` int NULL, `distillingId` int NULL, `fermentingId` int NULL, UNIQUE INDEX `IDX_98086f14e190574534d5129cd7` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `processes` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `nombre` varchar(150) NOT NULL, `descripcion` text NOT NULL, `html` text NULL, UNIQUE INDEX `IDX_348fc66d6e8d149602607414b5` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `productTastings` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `comment` text NOT NULL, `userId` int NULL, `productId` int NULL, UNIQUE INDEX `IDX_a8f77b7fa31430efcd1efdd368` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `images` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `title` varchar(150) NOT NULL, `description` varchar(150) NOT NULL, `fieldname` varchar(150) NOT NULL, `originalname` varchar(150) NOT NULL, `encoding` varchar(150) NOT NULL, `mimetype` varchar(150) NOT NULL, `destination` varchar(150) NOT NULL, `filename` varchar(150) NOT NULL, `path` text NOT NULL, `size` int NOT NULL, `productId` int NULL, `houseId` int NULL, `brandId` int NULL, `masterId` int NULL, `regionId` int NULL, `agaveId` int NULL, `brandlogoId` int NULL, `processeId` int NULL, `productTastingId` int NULL, UNIQUE INDEX `IDX_a5bd7999989d2a6bb88924613b` (`uuid`), UNIQUE INDEX `REL_81c5962e9d6fdfc6c0f91d397a` (`brandlogoId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `definitions` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `type` varchar(50) NOT NULL DEFAULT 'catalogo', `name` varchar(50) NOT NULL, `title` varchar(50) NOT NULL, `label` varchar(50) NOT NULL DEFAULT 'Valor', `vieworder` int NOT NULL DEFAULT '0', `icon` varchar(50) NOT NULL DEFAULT 'close', UNIQUE INDEX `IDX_1c23bd66a25342994b22d140d9` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `brandLikes` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `userId` int NULL, `brandId` int NULL, UNIQUE INDEX `IDX_6679c1401d21c0a586f296aaaa` (`uuid`), UNIQUE INDEX `brand_likes` (`userId`, `brandId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `brandRatings` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `rating` float NOT NULL, `userId` int NULL, `brandId` int NULL, UNIQUE INDEX `IDX_dbc16d26e98b947c840108b5ae` (`uuid`), UNIQUE INDEX `brand_likes` (`userId`, `brandId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `emails` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `name` text NOT NULL, `email` text NOT NULL, `subject` text NOT NULL, `message` text NOT NULL, UNIQUE INDEX `IDX_ee7a49479fc4a5c47be7abc0ca` (`uuid`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `houseLikes` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `userId` int NULL, `houseId` int NULL, UNIQUE INDEX `IDX_fc739dc5d27f5859f17dcc8c6e` (`uuid`), UNIQUE INDEX `house_likes` (`userId`, `houseId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `houseRatings` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `rating` float NOT NULL, `userId` int NULL, `houseId` int NULL, UNIQUE INDEX `IDX_3683a53973431d4765ece745cf` (`uuid`), UNIQUE INDEX `house_likes` (`userId`, `houseId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `productRatings` (`id` int NOT NULL AUTO_INCREMENT, `uuid` varchar(36) NOT NULL, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `active` tinyint NOT NULL DEFAULT 1, `rating` float NOT NULL, `userId` int NULL, `productId` int NULL, UNIQUE INDEX `IDX_1d7438dba1f8893a9ab1c1de64` (`uuid`), UNIQUE INDEX `product_likes` (`userId`, `productId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `profiles_rules_rules` (`profilesId` int NOT NULL, `rulesId` int NOT NULL, INDEX `IDX_5f5a5b67c9b4b2e8b1aa2556f1` (`profilesId`), INDEX `IDX_0a911e7ebe557b780027e0dd34` (`rulesId`), PRIMARY KEY (`profilesId`, `rulesId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `products_processes_processes` (`productsId` int NOT NULL, `processesId` int NOT NULL, INDEX `IDX_c89ff073084f56133b587ad447` (`productsId`), INDEX `IDX_72cf89f8f82bbc2ef8dc9896b1` (`processesId`), PRIMARY KEY (`productsId`, `processesId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `products_shops_shops` (`productsId` int NOT NULL, `shopsId` int NOT NULL, INDEX `IDX_bb07c77ae7287cae7da2dc6a83` (`productsId`), INDEX `IDX_6d029996d4e19376e0e44c687f` (`shopsId`), PRIMARY KEY (`productsId`, `shopsId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `products_agaves_agaves` (`productsId` int NOT NULL, `agavesId` int NOT NULL, INDEX `IDX_db59d15596b96d5cacf99f6279` (`productsId`), INDEX `IDX_4942e6c06987badb7c48556287` (`agavesId`), PRIMARY KEY (`productsId`, `agavesId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `products_flavors_flavors` (`productsId` int NOT NULL, `flavorsId` int NOT NULL, INDEX `IDX_4547920f9b9cdde286a3ce290d` (`productsId`), INDEX `IDX_116c17586f143934ed3e9f1f75` (`flavorsId`), PRIMARY KEY (`productsId`, `flavorsId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `products_aromas_flavors` (`productsId` int NOT NULL, `flavorsId` int NOT NULL, INDEX `IDX_b822defea45f93d35b57d694ef` (`productsId`), INDEX `IDX_b915602a8db784c4b121a16cfb` (`flavorsId`), PRIMARY KEY (`productsId`, `flavorsId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `processes_cookings_cooking` (`processesId` int NOT NULL, `cookingId` int NOT NULL, INDEX `IDX_0d1ca5bc98ce71516b92db4fba` (`processesId`), INDEX `IDX_7503df0c247cb1cb3be26a1aed` (`cookingId`), PRIMARY KEY (`processesId`, `cookingId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `processes_millings_milling` (`processesId` int NOT NULL, `millingId` int NOT NULL, INDEX `IDX_8f9c182d2fb4fe2c1bc71be61d` (`processesId`), INDEX `IDX_5481ac3b6f60db141f9661600c` (`millingId`), PRIMARY KEY (`processesId`, `millingId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `processes_fermentings_fermenting` (`processesId` int NOT NULL, `fermentingId` int NOT NULL, INDEX `IDX_f5e2f3af8b51e300a1775cb23e` (`processesId`), INDEX `IDX_cadfaed6de04fa330ae06a1bfb` (`fermentingId`), PRIMARY KEY (`processesId`, `fermentingId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `processes_distillings_distilling` (`processesId` int NOT NULL, `distillingId` int NOT NULL, INDEX `IDX_fd397e07abbde787e175cad98b` (`processesId`), INDEX `IDX_148309822d8b843cea3d284b1b` (`distillingId`), PRIMARY KEY (`processesId`, `distillingId`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `users` ADD CONSTRAINT `FK_b1bda35cdb9a2c1b777f5541d87` FOREIGN KEY (`profileId`) REFERENCES `profiles`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `users` ADD CONSTRAINT `FK_2735f0f46d5ffa988230f05a3ba` FOREIGN KEY (`houseId`) REFERENCES `houses`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `houseComments` ADD CONSTRAINT `FK_fa462e8e9dbac919c14cf0b4ab5` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `houseComments` ADD CONSTRAINT `FK_0c698cd06a8886e37aff66e1b65` FOREIGN KEY (`houseId`) REFERENCES `houses`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `masters` ADD CONSTRAINT `FK_bb43f8ee2b6de1bb1ef00d36718` FOREIGN KEY (`houseId`) REFERENCES `houses`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `brandComments` ADD CONSTRAINT `FK_f7ed6da3246f4c7715a35c439c6` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `brandComments` ADD CONSTRAINT `FK_d4b2f12910013398cd4c0458748` FOREIGN KEY (`brandId`) REFERENCES `brands`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `brands` ADD CONSTRAINT `FK_ab60d158f2570997a7dce7141a1` FOREIGN KEY (`houseId`) REFERENCES `houses`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `productComments` ADD CONSTRAINT `FK_566085adabda80ba1dd5c8c9bd5` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `productComments` ADD CONSTRAINT `FK_1a3cdbd5c0a93cdbe8ab1150ee9` FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `productFavorites` ADD CONSTRAINT `FK_38c7dd2a3b3d01e50bf87098a73` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `productFavorites` ADD CONSTRAINT `FK_89aa6dd6e8e97df54c0553cf93f` FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `productLikes` ADD CONSTRAINT `FK_791f5544a466ed82af1ddc4593e` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `productLikes` ADD CONSTRAINT `FK_f5cdc68c864cec274dd7bac5d36` FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_ea86d0c514c4ecbb5694cbf57df` FOREIGN KEY (`brandId`) REFERENCES `brands`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_4114f73e48fd06a2c0e07c54ef1` FOREIGN KEY (`masterId`) REFERENCES `masters`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_91a04dae1671fe55327cc9e220c` FOREIGN KEY (`regionId`) REFERENCES `regions`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_475bd35b6924feb045b8046b20d` FOREIGN KEY (`mezcalTypeId`) REFERENCES `mezcalTypes`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_7039c8e0c59c4ea051c98f699c4` FOREIGN KEY (`cookingId`) REFERENCES `cooking`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_7cd7992f43ca93dcd348f59edde` FOREIGN KEY (`millingId`) REFERENCES `milling`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_31dda0b648664ca0bd1b3d9b4a2` FOREIGN KEY (`distillingId`) REFERENCES `distilling`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products` ADD CONSTRAINT `FK_10dd153fe638d518a3a279a70c9` FOREIGN KEY (`fermentingId`) REFERENCES `fermenting`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `productTastings` ADD CONSTRAINT `FK_3dbb7501a275ef122dfe131267a` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `productTastings` ADD CONSTRAINT `FK_c0103930657ca7d47e92571b1aa` FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `images` ADD CONSTRAINT `FK_7af50639264735c79e918af6089` FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `images` ADD CONSTRAINT `FK_aba296a1bfa4e14149bec1287f1` FOREIGN KEY (`houseId`) REFERENCES `houses`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `images` ADD CONSTRAINT `FK_81c5962e9d6fdfc6c0f91d397a4` FOREIGN KEY (`brandlogoId`) REFERENCES `brands`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `images` ADD CONSTRAINT `FK_accba4b14fe0842e172705c7962` FOREIGN KEY (`brandId`) REFERENCES `brands`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `images` ADD CONSTRAINT `FK_3aa00a8c195e9adc6cd49485391` FOREIGN KEY (`masterId`) REFERENCES `masters`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `images` ADD CONSTRAINT `FK_37574b3414c1fd39221b3e3b428` FOREIGN KEY (`regionId`) REFERENCES `regions`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `images` ADD CONSTRAINT `FK_b3be8fc5d3de64c83ef6568c0b8` FOREIGN KEY (`agaveId`) REFERENCES `agaves`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `images` ADD CONSTRAINT `FK_7e8c9eaa7977cbc5c77b0ba717d` FOREIGN KEY (`processeId`) REFERENCES `processes`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `images` ADD CONSTRAINT `FK_8b17de4415ba8bcdc6108d045d9` FOREIGN KEY (`productTastingId`) REFERENCES `productTastings`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `brandLikes` ADD CONSTRAINT `FK_7952e946e49be98e6aae1dd1212` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `brandLikes` ADD CONSTRAINT `FK_c7d5dd745bd8a8742b7e91b1b62` FOREIGN KEY (`brandId`) REFERENCES `brands`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `brandRatings` ADD CONSTRAINT `FK_efd560040f82a265eda05a2cd19` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `brandRatings` ADD CONSTRAINT `FK_a77ab846f33bfdd7dcab4db7002` FOREIGN KEY (`brandId`) REFERENCES `brands`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `houseLikes` ADD CONSTRAINT `FK_7836da7a67800f6707fd4770bab` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `houseLikes` ADD CONSTRAINT `FK_283e7fa5a6d29c34a4c5c4b3c7c` FOREIGN KEY (`houseId`) REFERENCES `houses`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `houseRatings` ADD CONSTRAINT `FK_106d25bab795a87e1f7b4ab7fbd` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `houseRatings` ADD CONSTRAINT `FK_c3459e927cf76bdeeffd68749e1` FOREIGN KEY (`houseId`) REFERENCES `houses`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `productRatings` ADD CONSTRAINT `FK_b695165044661b2a7036af9fb2b` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `productRatings` ADD CONSTRAINT `FK_1250bb6a10cd6f361ba56cc9469` FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `profiles_rules_rules` ADD CONSTRAINT `FK_5f5a5b67c9b4b2e8b1aa2556f1b` FOREIGN KEY (`profilesId`) REFERENCES `profiles`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `profiles_rules_rules` ADD CONSTRAINT `FK_0a911e7ebe557b780027e0dd34b` FOREIGN KEY (`rulesId`) REFERENCES `rules`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products_processes_processes` ADD CONSTRAINT `FK_c89ff073084f56133b587ad447f` FOREIGN KEY (`productsId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products_processes_processes` ADD CONSTRAINT `FK_72cf89f8f82bbc2ef8dc9896b11` FOREIGN KEY (`processesId`) REFERENCES `processes`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products_shops_shops` ADD CONSTRAINT `FK_bb07c77ae7287cae7da2dc6a833` FOREIGN KEY (`productsId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products_shops_shops` ADD CONSTRAINT `FK_6d029996d4e19376e0e44c687f5` FOREIGN KEY (`shopsId`) REFERENCES `shops`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products_agaves_agaves` ADD CONSTRAINT `FK_db59d15596b96d5cacf99f6279e` FOREIGN KEY (`productsId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products_agaves_agaves` ADD CONSTRAINT `FK_4942e6c06987badb7c48556287b` FOREIGN KEY (`agavesId`) REFERENCES `agaves`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products_flavors_flavors` ADD CONSTRAINT `FK_4547920f9b9cdde286a3ce290da` FOREIGN KEY (`productsId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products_flavors_flavors` ADD CONSTRAINT `FK_116c17586f143934ed3e9f1f75c` FOREIGN KEY (`flavorsId`) REFERENCES `flavors`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products_aromas_flavors` ADD CONSTRAINT `FK_b822defea45f93d35b57d694eff` FOREIGN KEY (`productsId`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `products_aromas_flavors` ADD CONSTRAINT `FK_b915602a8db784c4b121a16cfb2` FOREIGN KEY (`flavorsId`) REFERENCES `flavors`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `processes_cookings_cooking` ADD CONSTRAINT `FK_0d1ca5bc98ce71516b92db4fbaa` FOREIGN KEY (`processesId`) REFERENCES `processes`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `processes_cookings_cooking` ADD CONSTRAINT `FK_7503df0c247cb1cb3be26a1aedc` FOREIGN KEY (`cookingId`) REFERENCES `cooking`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `processes_millings_milling` ADD CONSTRAINT `FK_8f9c182d2fb4fe2c1bc71be61da` FOREIGN KEY (`processesId`) REFERENCES `processes`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `processes_millings_milling` ADD CONSTRAINT `FK_5481ac3b6f60db141f9661600c4` FOREIGN KEY (`millingId`) REFERENCES `milling`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `processes_fermentings_fermenting` ADD CONSTRAINT `FK_f5e2f3af8b51e300a1775cb23e6` FOREIGN KEY (`processesId`) REFERENCES `processes`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `processes_fermentings_fermenting` ADD CONSTRAINT `FK_cadfaed6de04fa330ae06a1bfb3` FOREIGN KEY (`fermentingId`) REFERENCES `fermenting`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `processes_distillings_distilling` ADD CONSTRAINT `FK_fd397e07abbde787e175cad98be` FOREIGN KEY (`processesId`) REFERENCES `processes`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `processes_distillings_distilling` ADD CONSTRAINT `FK_148309822d8b843cea3d284b1b2` FOREIGN KEY (`distillingId`) REFERENCES `distilling`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `processes_distillings_distilling` DROP FOREIGN KEY `FK_148309822d8b843cea3d284b1b2`");
        await queryRunner.query("ALTER TABLE `processes_distillings_distilling` DROP FOREIGN KEY `FK_fd397e07abbde787e175cad98be`");
        await queryRunner.query("ALTER TABLE `processes_fermentings_fermenting` DROP FOREIGN KEY `FK_cadfaed6de04fa330ae06a1bfb3`");
        await queryRunner.query("ALTER TABLE `processes_fermentings_fermenting` DROP FOREIGN KEY `FK_f5e2f3af8b51e300a1775cb23e6`");
        await queryRunner.query("ALTER TABLE `processes_millings_milling` DROP FOREIGN KEY `FK_5481ac3b6f60db141f9661600c4`");
        await queryRunner.query("ALTER TABLE `processes_millings_milling` DROP FOREIGN KEY `FK_8f9c182d2fb4fe2c1bc71be61da`");
        await queryRunner.query("ALTER TABLE `processes_cookings_cooking` DROP FOREIGN KEY `FK_7503df0c247cb1cb3be26a1aedc`");
        await queryRunner.query("ALTER TABLE `processes_cookings_cooking` DROP FOREIGN KEY `FK_0d1ca5bc98ce71516b92db4fbaa`");
        await queryRunner.query("ALTER TABLE `products_aromas_flavors` DROP FOREIGN KEY `FK_b915602a8db784c4b121a16cfb2`");
        await queryRunner.query("ALTER TABLE `products_aromas_flavors` DROP FOREIGN KEY `FK_b822defea45f93d35b57d694eff`");
        await queryRunner.query("ALTER TABLE `products_flavors_flavors` DROP FOREIGN KEY `FK_116c17586f143934ed3e9f1f75c`");
        await queryRunner.query("ALTER TABLE `products_flavors_flavors` DROP FOREIGN KEY `FK_4547920f9b9cdde286a3ce290da`");
        await queryRunner.query("ALTER TABLE `products_agaves_agaves` DROP FOREIGN KEY `FK_4942e6c06987badb7c48556287b`");
        await queryRunner.query("ALTER TABLE `products_agaves_agaves` DROP FOREIGN KEY `FK_db59d15596b96d5cacf99f6279e`");
        await queryRunner.query("ALTER TABLE `products_shops_shops` DROP FOREIGN KEY `FK_6d029996d4e19376e0e44c687f5`");
        await queryRunner.query("ALTER TABLE `products_shops_shops` DROP FOREIGN KEY `FK_bb07c77ae7287cae7da2dc6a833`");
        await queryRunner.query("ALTER TABLE `products_processes_processes` DROP FOREIGN KEY `FK_72cf89f8f82bbc2ef8dc9896b11`");
        await queryRunner.query("ALTER TABLE `products_processes_processes` DROP FOREIGN KEY `FK_c89ff073084f56133b587ad447f`");
        await queryRunner.query("ALTER TABLE `profiles_rules_rules` DROP FOREIGN KEY `FK_0a911e7ebe557b780027e0dd34b`");
        await queryRunner.query("ALTER TABLE `profiles_rules_rules` DROP FOREIGN KEY `FK_5f5a5b67c9b4b2e8b1aa2556f1b`");
        await queryRunner.query("ALTER TABLE `productRatings` DROP FOREIGN KEY `FK_1250bb6a10cd6f361ba56cc9469`");
        await queryRunner.query("ALTER TABLE `productRatings` DROP FOREIGN KEY `FK_b695165044661b2a7036af9fb2b`");
        await queryRunner.query("ALTER TABLE `houseRatings` DROP FOREIGN KEY `FK_c3459e927cf76bdeeffd68749e1`");
        await queryRunner.query("ALTER TABLE `houseRatings` DROP FOREIGN KEY `FK_106d25bab795a87e1f7b4ab7fbd`");
        await queryRunner.query("ALTER TABLE `houseLikes` DROP FOREIGN KEY `FK_283e7fa5a6d29c34a4c5c4b3c7c`");
        await queryRunner.query("ALTER TABLE `houseLikes` DROP FOREIGN KEY `FK_7836da7a67800f6707fd4770bab`");
        await queryRunner.query("ALTER TABLE `brandRatings` DROP FOREIGN KEY `FK_a77ab846f33bfdd7dcab4db7002`");
        await queryRunner.query("ALTER TABLE `brandRatings` DROP FOREIGN KEY `FK_efd560040f82a265eda05a2cd19`");
        await queryRunner.query("ALTER TABLE `brandLikes` DROP FOREIGN KEY `FK_c7d5dd745bd8a8742b7e91b1b62`");
        await queryRunner.query("ALTER TABLE `brandLikes` DROP FOREIGN KEY `FK_7952e946e49be98e6aae1dd1212`");
        await queryRunner.query("ALTER TABLE `images` DROP FOREIGN KEY `FK_8b17de4415ba8bcdc6108d045d9`");
        await queryRunner.query("ALTER TABLE `images` DROP FOREIGN KEY `FK_7e8c9eaa7977cbc5c77b0ba717d`");
        await queryRunner.query("ALTER TABLE `images` DROP FOREIGN KEY `FK_b3be8fc5d3de64c83ef6568c0b8`");
        await queryRunner.query("ALTER TABLE `images` DROP FOREIGN KEY `FK_37574b3414c1fd39221b3e3b428`");
        await queryRunner.query("ALTER TABLE `images` DROP FOREIGN KEY `FK_3aa00a8c195e9adc6cd49485391`");
        await queryRunner.query("ALTER TABLE `images` DROP FOREIGN KEY `FK_accba4b14fe0842e172705c7962`");
        await queryRunner.query("ALTER TABLE `images` DROP FOREIGN KEY `FK_81c5962e9d6fdfc6c0f91d397a4`");
        await queryRunner.query("ALTER TABLE `images` DROP FOREIGN KEY `FK_aba296a1bfa4e14149bec1287f1`");
        await queryRunner.query("ALTER TABLE `images` DROP FOREIGN KEY `FK_7af50639264735c79e918af6089`");
        await queryRunner.query("ALTER TABLE `productTastings` DROP FOREIGN KEY `FK_c0103930657ca7d47e92571b1aa`");
        await queryRunner.query("ALTER TABLE `productTastings` DROP FOREIGN KEY `FK_3dbb7501a275ef122dfe131267a`");
        await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_10dd153fe638d518a3a279a70c9`");
        await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_31dda0b648664ca0bd1b3d9b4a2`");
        await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_7cd7992f43ca93dcd348f59edde`");
        await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_7039c8e0c59c4ea051c98f699c4`");
        await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_475bd35b6924feb045b8046b20d`");
        await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_91a04dae1671fe55327cc9e220c`");
        await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_4114f73e48fd06a2c0e07c54ef1`");
        await queryRunner.query("ALTER TABLE `products` DROP FOREIGN KEY `FK_ea86d0c514c4ecbb5694cbf57df`");
        await queryRunner.query("ALTER TABLE `productLikes` DROP FOREIGN KEY `FK_f5cdc68c864cec274dd7bac5d36`");
        await queryRunner.query("ALTER TABLE `productLikes` DROP FOREIGN KEY `FK_791f5544a466ed82af1ddc4593e`");
        await queryRunner.query("ALTER TABLE `productFavorites` DROP FOREIGN KEY `FK_89aa6dd6e8e97df54c0553cf93f`");
        await queryRunner.query("ALTER TABLE `productFavorites` DROP FOREIGN KEY `FK_38c7dd2a3b3d01e50bf87098a73`");
        await queryRunner.query("ALTER TABLE `productComments` DROP FOREIGN KEY `FK_1a3cdbd5c0a93cdbe8ab1150ee9`");
        await queryRunner.query("ALTER TABLE `productComments` DROP FOREIGN KEY `FK_566085adabda80ba1dd5c8c9bd5`");
        await queryRunner.query("ALTER TABLE `brands` DROP FOREIGN KEY `FK_ab60d158f2570997a7dce7141a1`");
        await queryRunner.query("ALTER TABLE `brandComments` DROP FOREIGN KEY `FK_d4b2f12910013398cd4c0458748`");
        await queryRunner.query("ALTER TABLE `brandComments` DROP FOREIGN KEY `FK_f7ed6da3246f4c7715a35c439c6`");
        await queryRunner.query("ALTER TABLE `masters` DROP FOREIGN KEY `FK_bb43f8ee2b6de1bb1ef00d36718`");
        await queryRunner.query("ALTER TABLE `houseComments` DROP FOREIGN KEY `FK_0c698cd06a8886e37aff66e1b65`");
        await queryRunner.query("ALTER TABLE `houseComments` DROP FOREIGN KEY `FK_fa462e8e9dbac919c14cf0b4ab5`");
        await queryRunner.query("ALTER TABLE `users` DROP FOREIGN KEY `FK_2735f0f46d5ffa988230f05a3ba`");
        await queryRunner.query("ALTER TABLE `users` DROP FOREIGN KEY `FK_b1bda35cdb9a2c1b777f5541d87`");
        await queryRunner.query("DROP INDEX `IDX_148309822d8b843cea3d284b1b` ON `processes_distillings_distilling`");
        await queryRunner.query("DROP INDEX `IDX_fd397e07abbde787e175cad98b` ON `processes_distillings_distilling`");
        await queryRunner.query("DROP TABLE `processes_distillings_distilling`");
        await queryRunner.query("DROP INDEX `IDX_cadfaed6de04fa330ae06a1bfb` ON `processes_fermentings_fermenting`");
        await queryRunner.query("DROP INDEX `IDX_f5e2f3af8b51e300a1775cb23e` ON `processes_fermentings_fermenting`");
        await queryRunner.query("DROP TABLE `processes_fermentings_fermenting`");
        await queryRunner.query("DROP INDEX `IDX_5481ac3b6f60db141f9661600c` ON `processes_millings_milling`");
        await queryRunner.query("DROP INDEX `IDX_8f9c182d2fb4fe2c1bc71be61d` ON `processes_millings_milling`");
        await queryRunner.query("DROP TABLE `processes_millings_milling`");
        await queryRunner.query("DROP INDEX `IDX_7503df0c247cb1cb3be26a1aed` ON `processes_cookings_cooking`");
        await queryRunner.query("DROP INDEX `IDX_0d1ca5bc98ce71516b92db4fba` ON `processes_cookings_cooking`");
        await queryRunner.query("DROP TABLE `processes_cookings_cooking`");
        await queryRunner.query("DROP INDEX `IDX_b915602a8db784c4b121a16cfb` ON `products_aromas_flavors`");
        await queryRunner.query("DROP INDEX `IDX_b822defea45f93d35b57d694ef` ON `products_aromas_flavors`");
        await queryRunner.query("DROP TABLE `products_aromas_flavors`");
        await queryRunner.query("DROP INDEX `IDX_116c17586f143934ed3e9f1f75` ON `products_flavors_flavors`");
        await queryRunner.query("DROP INDEX `IDX_4547920f9b9cdde286a3ce290d` ON `products_flavors_flavors`");
        await queryRunner.query("DROP TABLE `products_flavors_flavors`");
        await queryRunner.query("DROP INDEX `IDX_4942e6c06987badb7c48556287` ON `products_agaves_agaves`");
        await queryRunner.query("DROP INDEX `IDX_db59d15596b96d5cacf99f6279` ON `products_agaves_agaves`");
        await queryRunner.query("DROP TABLE `products_agaves_agaves`");
        await queryRunner.query("DROP INDEX `IDX_6d029996d4e19376e0e44c687f` ON `products_shops_shops`");
        await queryRunner.query("DROP INDEX `IDX_bb07c77ae7287cae7da2dc6a83` ON `products_shops_shops`");
        await queryRunner.query("DROP TABLE `products_shops_shops`");
        await queryRunner.query("DROP INDEX `IDX_72cf89f8f82bbc2ef8dc9896b1` ON `products_processes_processes`");
        await queryRunner.query("DROP INDEX `IDX_c89ff073084f56133b587ad447` ON `products_processes_processes`");
        await queryRunner.query("DROP TABLE `products_processes_processes`");
        await queryRunner.query("DROP INDEX `IDX_0a911e7ebe557b780027e0dd34` ON `profiles_rules_rules`");
        await queryRunner.query("DROP INDEX `IDX_5f5a5b67c9b4b2e8b1aa2556f1` ON `profiles_rules_rules`");
        await queryRunner.query("DROP TABLE `profiles_rules_rules`");
        await queryRunner.query("DROP INDEX `product_likes` ON `productRatings`");
        await queryRunner.query("DROP INDEX `IDX_1d7438dba1f8893a9ab1c1de64` ON `productRatings`");
        await queryRunner.query("DROP TABLE `productRatings`");
        await queryRunner.query("DROP INDEX `house_likes` ON `houseRatings`");
        await queryRunner.query("DROP INDEX `IDX_3683a53973431d4765ece745cf` ON `houseRatings`");
        await queryRunner.query("DROP TABLE `houseRatings`");
        await queryRunner.query("DROP INDEX `house_likes` ON `houseLikes`");
        await queryRunner.query("DROP INDEX `IDX_fc739dc5d27f5859f17dcc8c6e` ON `houseLikes`");
        await queryRunner.query("DROP TABLE `houseLikes`");
        await queryRunner.query("DROP INDEX `IDX_ee7a49479fc4a5c47be7abc0ca` ON `emails`");
        await queryRunner.query("DROP TABLE `emails`");
        await queryRunner.query("DROP INDEX `brand_likes` ON `brandRatings`");
        await queryRunner.query("DROP INDEX `IDX_dbc16d26e98b947c840108b5ae` ON `brandRatings`");
        await queryRunner.query("DROP TABLE `brandRatings`");
        await queryRunner.query("DROP INDEX `brand_likes` ON `brandLikes`");
        await queryRunner.query("DROP INDEX `IDX_6679c1401d21c0a586f296aaaa` ON `brandLikes`");
        await queryRunner.query("DROP TABLE `brandLikes`");
        await queryRunner.query("DROP INDEX `IDX_1c23bd66a25342994b22d140d9` ON `definitions`");
        await queryRunner.query("DROP TABLE `definitions`");
        await queryRunner.query("DROP INDEX `REL_81c5962e9d6fdfc6c0f91d397a` ON `images`");
        await queryRunner.query("DROP INDEX `IDX_a5bd7999989d2a6bb88924613b` ON `images`");
        await queryRunner.query("DROP TABLE `images`");
        await queryRunner.query("DROP INDEX `IDX_a8f77b7fa31430efcd1efdd368` ON `productTastings`");
        await queryRunner.query("DROP TABLE `productTastings`");
        await queryRunner.query("DROP INDEX `IDX_348fc66d6e8d149602607414b5` ON `processes`");
        await queryRunner.query("DROP TABLE `processes`");
        await queryRunner.query("DROP INDEX `IDX_98086f14e190574534d5129cd7` ON `products`");
        await queryRunner.query("DROP TABLE `products`");
        await queryRunner.query("DROP INDEX `IDX_895c479772745b4dd5e55e1452` ON `milling`");
        await queryRunner.query("DROP TABLE `milling`");
        await queryRunner.query("DROP INDEX `IDX_0d0f15acacb3a684f4815da6c7` ON `fermenting`");
        await queryRunner.query("DROP TABLE `fermenting`");
        await queryRunner.query("DROP INDEX `IDX_aae0770d4db841e9578c9b97bf` ON `distilling`");
        await queryRunner.query("DROP TABLE `distilling`");
        await queryRunner.query("DROP INDEX `IDX_34d3e15110d10debca394179b2` ON `cooking`");
        await queryRunner.query("DROP TABLE `cooking`");
        await queryRunner.query("DROP INDEX `product_likes` ON `productLikes`");
        await queryRunner.query("DROP INDEX `IDX_4c726761d40c6ed3afd0f310f2` ON `productLikes`");
        await queryRunner.query("DROP TABLE `productLikes`");
        await queryRunner.query("DROP INDEX `product_favorites` ON `productFavorites`");
        await queryRunner.query("DROP INDEX `IDX_12015674033f1e5f0d8c57c086` ON `productFavorites`");
        await queryRunner.query("DROP TABLE `productFavorites`");
        await queryRunner.query("DROP INDEX `IDX_9f52cb406e348e1039d7449179` ON `productComments`");
        await queryRunner.query("DROP TABLE `productComments`");
        await queryRunner.query("DROP INDEX `IDX_44741720475c1fd87b9bd52ce7` ON `mezcalTypes`");
        await queryRunner.query("DROP TABLE `mezcalTypes`");
        await queryRunner.query("DROP INDEX `IDX_072498f4079793b73da14c63ab` ON `shops`");
        await queryRunner.query("DROP TABLE `shops`");
        await queryRunner.query("DROP INDEX `IDX_c089087c9ead1061cb0b9f5704` ON `flavors`");
        await queryRunner.query("DROP TABLE `flavors`");
        await queryRunner.query("DROP INDEX `IDX_0a493669ddc4365a0339173e8c` ON `agaves`");
        await queryRunner.query("DROP TABLE `agaves`");
        await queryRunner.query("DROP INDEX `IDX_a624c5554287d4034798478a6b` ON `regions`");
        await queryRunner.query("DROP TABLE `regions`");
        await queryRunner.query("DROP INDEX `IDX_8502686214ddaf3c16aeb2475a` ON `brands`");
        await queryRunner.query("DROP TABLE `brands`");
        await queryRunner.query("DROP INDEX `IDX_a8acc9fa5069c8d546ac7b0e19` ON `brandComments`");
        await queryRunner.query("DROP TABLE `brandComments`");
        await queryRunner.query("DROP INDEX `IDX_3365dc20e45b6d2576db3d30a4` ON `houses`");
        await queryRunner.query("DROP INDEX `IDX_5a47aaa8bc31d505a3b16cad02` ON `houses`");
        await queryRunner.query("DROP TABLE `houses`");
        await queryRunner.query("DROP INDEX `IDX_3557a21feed9f2081e0678cef2` ON `masters`");
        await queryRunner.query("DROP TABLE `masters`");
        await queryRunner.query("DROP INDEX `IDX_1cb1775299c76dab26b0344dce` ON `houseComments`");
        await queryRunner.query("DROP TABLE `houseComments`");
        await queryRunner.query("DROP INDEX `IDX_97672ac88f789774dd47f7c8be` ON `users`");
        await queryRunner.query("DROP INDEX `IDX_951b8f1dfc94ac1d0301a14b7e` ON `users`");
        await queryRunner.query("DROP TABLE `users`");
        await queryRunner.query("DROP INDEX `IDX_4e9da7cade0e9edd393329bb32` ON `profiles`");
        await queryRunner.query("DROP INDEX `IDX_2c0c7196c89bdcc9b04f29f3fe` ON `profiles`");
        await queryRunner.query("DROP TABLE `profiles`");
        await queryRunner.query("DROP INDEX `IDX_ea1cb877c529e67a39e2be4657` ON `rules`");
        await queryRunner.query("DROP INDEX `IDX_b5749378ee460e67696a7518d4` ON `rules`");
        await queryRunner.query("DROP TABLE `rules`");
    }

}
