import { AgaveEntity } from './model/agave.entity';

export const AgavesToCreate: AgaveEntity[] = [
  {
    nombre: `Espadín`,
    nombresConocidos:[`Espadilla`, `doba-yej (maguey de flor)`, `maguey quixe`, `yahui xiuco (Mixteco)`, `yavi incoyo (Mixteco)`],
    nombreCientifico: `Ag. angustifolia. var. Angustifolia.`,
    distribucion: `De México a Panamá. Ampliamente distribuida en México. En Oaxaca se ha registrado en los distritos: Centro, Cuicatlán, Ejutla, Etla, Huajuapan, Ixtlán, Juchitán, Juxtlahuaca, Teotitlán, Teposcolula, Tlacolula, Tlaxiaco, Silacayoapam, Sola de Vega, Villa Alta, Yautepec y Zimatlán.`,
    descripcion: `Una de las especies más utilizadas para la producción de mezcal es la variedad “Espadín” de la especie A. angustifolia, cultivo de gran importancia para la industria mezcalera a nivel nacional y de un gran valor económico para Oaxaca. En un estudio realizado por el Sistema-Producto Maguey-Mezcal se menciona que los productores de mezcal prefieren esta especie y variedad, debido a que es de ciclo corto para su aprovechamiento, pues le toma de siete a nueve años en llegar a la madurez y produce piñas de mayor tamaño; razón por la que se cultiva en mayor extensión con fines comerciales, además de ser la variedad que aporta el mayor volumen de la materia prima para la elaboración de mezcal.`,
    comentarioTaxonomico: `Agave angustifolia es una especie que se distribuye de Sonora a Chiapas, muy variable morfológicamente a lo largo de su distribución. Gentry (1982), reconoce dos variedades para Oaxaca, Ag. angustifolia var. angustifolia y Ag. angustifolia var. rubescens. Las formas del noroeste de México, en los estados de Sonora, Chihuahua y Sinaloa, son más grandes en todos sus órganos vegetativos y reproductivos, con respecto a las de Guerrero-Puebla-Oaxaca, esto podría ser quizá suficiente para separarlas como dos especies, que además tienen floraciones en épocas diferentes. En el noroeste de México florece en invierno (diciembre-marzo), por el contrario las del sur lo hace en el verano (junio-agosto), sin embargo, es urgente un estudio completo del complejo.`,
    habitat: `Bosque tropical caducifolio, matorral xerófilo, palmar y zona de transición de los mismos con el bosque de Quercus; suelo calizo o volcánico. En elevaciones de 1000-1950 m.`,
    uso: `Producción de mezcal y fibras; las flores son comestibles; las inflorescencia se utiliza como forraje y los quiotes secos se emplean en la construcción (techos, paredes, cercos).`,
    probabilidadExistencia: `La especie se conoce de una buena parte del estado de Oaxaca, aunque de manera natural no es abundante. El espadín se cultiva ampliamente para la producción de mezcal en los Valles Centrales y Sierra Sur. Su distribución es la más amplia entre las especies de Agave y tiene una gran plasticidad morfológica. Sus variantes silvestres y cultivadas se utilizan como cerca viva, fuente de fibra, medicinas, bebida y alimento. Muchas de ellas tienen rasgos distintivos, lo que provocó el registro equivocado de más de 20 “especies” que son, a fin de cuentas, una sola: Agave angustifolia. Se propaga vegetativamente a través de hijuelos y bulbilos.`,
  },
  {
    nombre: `Espadilla.`,
    nombreCientifico: `Agave angustifolia var. rubescens (Salm-Dyck) Gentry.`,
    distribucion: `Endémica de México, se conoce de los estados de Guerrero, Jalisco y Oaxaca. En Oaxaca se ha registrado en los distritos: Cuicatlán, Etla, Pochutla, Tehuantepec y Yautepec.`,
    descripcion: ``,
    comentarioTaxonomico: `La variedad rubescens se diferencia de la variedad angustifolia por las rosetas laxas con hojas lineares, angostas, recurvadas, dientes del margen pequeños, frágiles y más cercanos entre sí, en ocasiones el margen tiene consistencia cartilaginosa; las flores también son más pequeñas. Por lo general habita sitios sombreados del bosque tropical caducifolio.`,
    habitat: `Bosque tropical caducifolio. En elevaciones de 900-1500 m.`,
    uso: `Se utiliza para elaborar mezcal.`,
    probabilidadExistencia: `Variedad escasa en la naturaleza, por lo que se emplea a baja escala para la producción de mezcal. Sin embargo, la extracción puede afectar la conservación de la especie.`,
  },
  {
    nombre: `Tobalá`,
    nombresConocidos: [ `papalomé`, `maguey papalomé`, `Papalometl`],
    nombreCientifico: `Agave potatorum Zucc.`,
    distribucion: `Se conoce de los estados de Oaxaca y Puebla. En Oaxaca en los distritos: Coixtlahuaca, Ejutla, Etla, Huajuapan, Ixtlán, Miahuatlán, Mixe, Nochixtlán, Ocotlán, Teotitlán, Tlacolula, Yautepec, Zaachila y Zimatlán.`,
    descripcion: `Es una de las especies que se utiliza en el estado de Oaxaca para la producción de mezcal. Es Característico de las partes interiores y secas de la Sierra Madre del Sur, valle de Tehuacán y  sierras de Oaxaca. Los murciélagos visitan sus flores otoñales, acarreando y mezclando el polen de poblaciones lejanas, que gracias a este intercambio son genéticamente similares. Es pariente del cupreata en proceso de diferenciación: habitan en sitios ecológicamente similares y sabemos que comparten genes. Depende de sus semillas para mantenerse, la mayor parte de la producción del mezcal tobalá depende de las poblaciones silvestres ubicadas en encinares y selvas bajas y que son muy apreciadas para este fin.`,
    comentarioTaxonomico: `La especie se caracteriza por presentar rosetas densas, con numerosas hojas aplanadas, margen con mamilas y dientes pequeños; inflorescencia paniculada con ramas primarias de 10-30 cm largo, distantes entre sí por 15.0-30.0 cm, presentes en la mitad o el tercio superior de la inflorescencia, las flores presentan tubo campanulado a ligeramente urceolado, los estambres insertos a la mitad del tubo o en el tercer cuarto superior; relación de tubo: tépalos1:1 o incluso el tubo llega a ser hasta 2 veces más largo que los tépalos.`,
    habitat: `Bosque tropical caducifolio, matorral xerófilo y transición de losmismos con el bosque de Quercus, en suelos sobre roca caliza. En elevacionesde 1300-2400 m.`,
    uso: `Se usa principalmente en la elaboración de mezcal, las flores se emplean en la alimentación al igual que el pedúnculo floral cuando ha comenzado su desarrollo y las hojas en la medicina tradicional para disminuir hinchazones y para el tratamiento de lesiones internas tanto de hombres como de animales domésticos.`,
    probabilidadExistencia: `El aprovechamiento de las plantas para la producción de mezcal es una amenaza para las poblaciones silvestres debido a que la totalidad de las plantas son extraídas del medio silvestre, además de que se aprovechan los individuos adultos, lo que reduce el número de reproductores, la producción de semillas y la regeneración natural de la especie. Otro factor de riesgo es la pérdida y destrucción del hábitat por el cambio de uso del suelo.`,
  },
  {
    nombre: `Cuishe`,
    nombresConocidos: [ `Cirial`, `tobasiche`, `maguey barril verde`, `maguey barril amarillo`, `maguey barril chino`, `tobasiche espina negra`, `bicuishe`, `marteño`, `madrecuishe`, `sierrudo`, `maguey barril gordo`, `candelillo`, `cachitún`, `becuela`],
    nombreCientifico: `Agave karwinskii Zucc.`,
    distribucion: `Endémica de México, se conoce de los estados de Puebla y Oaxaca. En Oaxaca en los distritos de los Valles Centrales: Ejutla, Ixtlán, Miahuatlán, Ocotlán, Sola de Vega, Teotitlán y Tlacolula, Zimatlán, Zaachila.`,
    descripcion: `Se trata de una especie de aspecto muy variable; cambian su altura y grosor, así como el color, el tamaño y la forma de sus hojas. Existen distintas subespecies, variedades o ecotipos de este maguey.`,
    comentarioTaxonomico: `Agave karwinskii se reconoce principalmente por el hábito arborescente y las hojas y flores relativamente pequeñas. Las formas cultivadas alcanzan hasta 3.0 m de alto, tienen un mayor número de hojas y son persistentes tanto las verdes como las secas, a lo largo de todo el tallo; el períodode floración es más amplio, de agosto a febrero.`,
    habitat: `Matorral xerófilo, bosque tropical caducifolio y protegida a lo largo de los caminos o bordeando terrenos de cultivo; sobre suelos calizos o sedimentario arenosos. En elevaciones de 900-1500 m.`,
    uso: `Se usa para la producción de mezcal. Por su tronco se le utiliza para leña y como cerca viva en la delimitación de terrenos; también se extraen fibras de sus hojas las inflorescencias jóvenes se utilizan como forraje; los botones florales se consumen como verdura en distintos guisos; de las hojas se extraen fibras (ixtle).`,
    probabilidadExistencia: `La importancia económica de la especie fomenta su protección y favorece su conservación y propagación.`,
  },
  {
    nombre: `Tepeztate`,
    nombresConocidos:[ `pichomel`, `pitzometl`, `pichometl`, `maguey curandero`, `huiscole`],
    nombreCientifico: `Agave marmorata Roezl.`,
    distribucion: `Endémica de México, se conoce de los estados de Oaxaca y Puebla. En Oaxaca en los distritos: Coixtlahuaca, Huajuapan, Miahuatlán, Tlacolula, Yautepec.`,
    descripcion: `Los colibríes y las calandrias se disputan el néctar de sus flores color naranja brillante, un alimento de gran valor que ofrecen  numerosas especies de Agave que florecen a lo largo de la temporada seca. Los murciélagos y mariposas nocturnas también dependen de este recurso. Comparte sus espacios con otros magueyes que florecen al mismo tiempo, como A. kerchovei y es probable que los polinizadores mezclen el polen de diferentes especies dando origen a plantas híbridas.`,
    comentarioTaxonomico: `Agave marmorata se reconoce por las rosetas laxas  con hojas verde-amarillentas a glaucas, ásperas al tacto, margen mamilado,  espinas cortas y robustas, inflorescencia paniculada muy laxa y flores pequeñas de color amarillo brillante.`,
    habitat: `Bosque tropical caducifolio, matorral xerófilo y zona de transición entre  estas dos comunidades y el bosque de Quercus, sobre suelos de origen calizo o  ígneo en elevaciones de 680-1600 m.`,
    uso: `Producción de mezcal y en algunas áreas se extrae aguamiel; los tallos y las inflorescencias jóvenes se consumen horneadas, ya secas se usan para cercos vivos y fabricar nidos de aves; el jugo de las hojas fresco se utiliza para aliviar úlceras, coágulos, asma, golpes y heridas, cocido se emplea como jarabe para curar tos y afecciones de los bronquios; las flores se usan para ornamentar iglesias, altares y casas durante las festividades de la Semana Mayor (Semana Santa), frescas se aprovechan como forraje para el ganado, y los botones florales o “cacayas” se consumen guisados como verdura.`,
    probabilidadExistencia: `La pérdida y degradación del hábitat son el principal factor de riesgo para las poblaciones silvestres, además del aprovechamiento para la producción de mezcal. La planta es muy apreciada como ornamental.`,
  },
  {
    nombre: `Tobalá`,
    nombresConocidos: [ `bilía`, `dób-bÉ`, `duabla`, `dób-zán (Zapoteco)`, `chato`, `papalometl`],
    nombreCientifico: `Agave seemanniana Jacobi, 1868.`,
    distribucion: `México a Nicaragua. En México se conoce de los estados de Chiapas y Oaxaca. En Oaxaca se ha registrado en los distritos: Cuicatlán, Miahuatlán, Pochutla, Sola de Vega, Tehuantepec y Tlaxiaco.`,
    descripcion: `Suele confundirse con Agave potatorum, especie de rosetas pequeñas e inflorescencias con menor número de ramas y más cortas.`,
    comentarioTaxonomico: `A. seemanniana se caracteriza por presentar rosetas laxas, mayores de 1.0 m alto, pocas hojas recurvadas, espatuladas a ampliamente lanceoladas, margen con mamilas prominentes y dientes de base amplia y 43 decurrentes, la inflorescencia posee ramas primarias, secundarias y ocasionalmente terciarias, las flores se caracterizan por los tubos cortos con los filamentos insertos 1.0-2.0(-3.0) mm por debajo de la boca del tubo, los estambres son relativamente cortos, ya que sobrepasan al tubo por 1.5-2.5 cm.`,
    habitat: `Bosque tropical caducifolio y ecotonía con bosque de Quercus-Pinus, en sustratos arenosos derivados de rocas calizas. En elevaciones de700-1700 m.`,
    uso: `Se usa para la producción de mezcal. Las inflorescencias como forraje; la planta completa se emplea como cerco vivo; la espina terminal se usa para neutralizar las picaduras de víbora haciendo incisiones alrededor de la herida.`,
    probabilidadExistencia: `El aprovechamiento de las poblaciones silvestres para obtener las plantas adultas para la producción de mezcal es la principal amenaza para la permanencia de la especie.`,
  },
  {
    nombre: `Mexicano`,
    nombresConocidos:[ `espadilla`, `espadín`, `barril gordo`, `maguey mexicano`],
    nombreCientifico: `Agave rhodacanthaTrel.`,
    distribucion: `Endémica de México, se conoce de Sonora a Oaxaca. En Oaxaca en los distritos: Ejutla, Huajuapan, Miahuatlán, Nochixtlán, Tlacolula, Silacayoapam y Zimatlán.`,
    descripcion: `De Sonora a Oaxaca, esta planta solitaria se encuentra en los pies de monte,  cuyos suelos someros y ricos en materia orgánica aportan los nutrientes que requiere para alcanzar sus impresionantes dimensiones.`,
    comentarioTaxonomico: `Agave rhodacantha es difícil de caracterizar por el  escaso material de herbario disponible. Se diferencia de Ag. angustifolia por las  rosetas grandes con numerosas hojas, largas y rígidas, dientes grandes y  robustos, cercanos entre sí; la inflorescencia grande y vigorosa, con ramas de  mayor longitud. Gentry (1982) menciona que las cápsulas son largamente  estipitadas, no se aprecia este carácter en los materiales de la región.`,
    habitat: `Bosque tropical caducifolio y matorral xerófilo. En elevaciones de 1750-2080 m.`,
    uso: `Producción de mezcal.  las inflorescencias jóvenes se utilizan como forraje; los botones florales se consumen como verdura en distintos guisos; de las hojas  se extraen fibras (ixtle).`,
    probabilidadExistencia: `Especie protegida por su importancia económica. Se propaga vegetativamente, sembrando los hijuelos a la orilla de los terrenos, huertas y en las cercanías de las casas.`,
  },
  {
    nombre: `Jabalí`,
    nombresConocidos:[ `Jabalín`, `maguey de escobeta`, `maguey de reata`, `maguey duro`, `maguey de lazo`],
    nombreCientifico: `Agave convallis Trel.`,
    distribucion: `En Oaxaca se ha registrado en los distritos: Cuicatlán, Etla, Huajuapan, Miahuatlán, Nochixtlán, Sola de Vega, Teposcolula, Tlacolula, Tlaxiaco, Yautepec.`,
    descripcion: ``,
    comentarioTaxonomico: `Agave convallis se diferencia de A. kerchovei por la roseta con mayor número de hojas; hojas más cortas, ampliamente lanceoladas o  lanceoladas, 4-10 veces más largas que anchas (vs 9-15 veces), dientes ausentes en el ápice por 5.0-15.0(-35.0) cm (vs 15.0-22.0(-50.0)), más cercanos entre sí,  bractéolas más largas que la flor; flores con tépalos oblongos, cápsulas obovoides y semillas más grandes. Además, Agave convallis crece en sitios más elevados,  en bosque de Quercus o matorral xerófilo sobre diferentes tipos de suelos. Gentry (1982), consideró esta especie como sinónimo de Agave kerchovei señalando que  su ejemplar No. 20278 era sólo una forma vigorosa de esta especie, sin embargo, las características morfológicas de las plantas, su distribución geográfica y altitudinal, época de floración y el hábitat, permiten separarlas como especies.`,
    habitat: `Bosque de Quercus, matorral xerófilo, selva baja caducifolia, matorral de Juniperus, zona de transición de bosque de galería y selva baja caducifolia; sobre suelos de origen ígneo y calcáreos; en laderas rocosas, y en cultivo. En elevaciones de 1800-2640 m.`,
    uso: `La fibra extraída de las hojas se utilizó para elaborar localmente cuerdas y cordeles, práctica que se está perdiendo en la actualidad. También se ha utilizado para elaborar Mezcal.`,
    probabilidadExistencia: `La especie es abundante en su área de distribución, sus poblaciones están conformadas por individuos de distintas edades. Aun cuando fue una especie aprovechada por su fibra (ixtle), usada para elaborar cuerdas, costales, lazos entre otros artículos, con fines de autoconsumo y comerciales, en la actualidad este uso se esta perdidendo lo que ha favorecido la formación de grandes colonias densas en su área de distribución natural.`,
  },
  {
    nombre: `Maguey de pulque`,
    nombresConocidos: [`Maguey manso`, `maguey mano ancha`, `yavi cui (maguey verde)`, `exmo´tstsaajts (maguey de base ancha) (Mixe)`],
    nombreCientifico: `Agave salmiana Otto ex Salm-Dyck subsp. salmiana.`,
    distribucion: `Endémica de México, se distribuye de los estados de Durango y Coahuila a Chiapas. En Oaxaca se ha registrado de los distritos Coixtlahuaca, Huajuapan, Juxtlahuaca, Mixe, Nochixtlán, Teposcolula, Teotitlán, Tlaxiaco.`,
    descripcion: `En el centro de México, es un agave pulquero por excelencia; fue deificada como Mayahuel. La subespecie crassispina, más pequeña y delgada, es propia de los matorrales y pastizales de la Meseta Central. El manejo de este maguey se caracteriza por la castración de la yema floral o cogollo, seguida de un periodo de reposo en campo de seis meses a dos años en que la planta concentra azúcares antes de la cosecha. En la segunda mitad del siglo XIX las haciendas del altiplano recibían mayores ingresos por mezcal que por cosechas y ganado, y su producción llegó a exceder a la del vino mezcal de Tequila.`,
    comentarioTaxonomico: `El nombre de la subespecie se aplica principalmente a las grandes plantas cultivadas o asilvestradas, que se explotan para la producción de pulque. Se diferencia de la subespecie tehuacanensis y la subespecie crassispina por ser plantas más grandes, masivas, con mayor número de hojas, con margen recto a ondulado y dientes más pequeños, las inflorescencias,son más altas y robustas, con ramas más largas, hasta de cuarto orden. Sin embargo, existen múltiples formas obtenidas del cruzamiento entre las subespecies.`,
    habitat: `Cultivada o en bordes del bosque de Quercus-Pinus, bosque tropical caducifolio y matorral xerófilo, sobre suelos diversos. Elevaciones de 1500-2600 m.`,
    uso: `Se utiliza principalmente para producir aguamiel y pulque; como cerco vivo para delimitar terrenos y huertos; las inflorescencias ocasionalmente se aprovechan como forraje y el pedúnculo seco o quiote para construcción (techos, paredes y cercos.`,
    probabilidadExistencia: `Especie protegida por su importancia económica. Se propaga vegetativamente, sembrando los hijuelos a la orilla de los terrenos, huertas y en las cercanías de las casas.`,
  },
  {
    nombre: `Mezcal maguey ceniza`,
    nombresConocidos: [ `maguey de Castilla`, `arroqueño`, `xolo`, `maguey sierra negra`, `maguey de rayo`, `maguey xolo blanco`],
    nombreCientifico: `Agave americana var. oaxacensis Gentry.`,
    distribucion: `Endémica de México, se conoce del estado de Oaxaca en los distritos: Centro, Cuicatlán, Ejutla, Huajuapan, Ixtlán, Nochixtlán, Ocotlán, Sola de Vega y Tlacolula.`,
    descripcion: `Dentro de la especie Agave americana la variedad oaxacensis se conoce únicamente domesticada en la zona donde se unen el valle de Tehuacán y el extremo oriental de la cuenca del Balsas. Se distingue por sus hojas blanquecinas y el gran tamaño de la inflorescencia, de las flores y los frutos. Se cultiva en traspatio aprovechando sus hijuelos para formar cercas vivas y extraer fibra de sus largas hojas. La producción de mezcal a partir e esta variedad es limitada, ya que tarda hasta 20 años en madurar.`,
    comentarioTaxonomico: `La variedad oaxacensis se diferencia de la variedad americana por las rosetas con mayor número de hojas; hojas lineares de base amplia, dientes pequeños en el margen; inflorescencias grandes con un mayor número de ramas, flores y cápsulas de mayor tamaño (Gentry, 1982).`,
    habitat: `Cultivada. En elevaciones de 1500-1800 m.`,
    uso: `Principalmente para la producción de mezcal. Las fibras (ixtle) extraídas de las hojas se usan para la elaboración de cuerdas y el quiote seco se utiliza para la construcción de techos, paredes y cercos.`,
    probabilidadExistencia: `Especie protegida por su importancia económica. Se propaga vegetativamente a través de hijuelos que se siembran a la orilla de los terrenos, huertas y en las cercanías de las casas.`,
  },
];
